#!/bin/bash
# Register and reset qemu for multi arch building
echo "=-=-=-=-= Build Setup =-=-=-=-="
docker buildx version
docker buildx ls
docker buildx create --name multiarch --driver docker-container \
  --platform linux/amd64,linux/arm64,linux/arm/v7 \
  --use
docker run --rm --privileged tonistiigi/binfmt --install all
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
echo "=-=-=-=-= Build Inspect =-=-=-=-="
docker buildx inspect --bootstrap --builder multiarch

